### PR TITLE
Design contests should not involve contracts

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by ColinMaudry** [comment]
At no point in the OCDS data we know it's a design contest and that prizes, and not contract, are awarded, right?

**Comment by ColinMaudry** [comment]
We know it from the `tender` release, because it has a `tender.designContest`... I'm not sure it's obvious enough for a clueless data explorer, especially if they only look at the `award` release..

**Comment by jpmckinney** [comment]
We can consider using `initiationType` to indicate that it is a substantially different procedure.

**Comment by ColinMaudry** [comment]
Do you mean using `initiationType` = "designContest" instead of "tender"? We're still using a "tender" to initiate the procedure, meaning we call for participant. It's indeed a special type of tender.

**Comment by jpmckinney** [comment]
Yes, I was thinking of setting initiationType = "designContest", but as you say, it is perhaps not so dramatically different, and "tender" maybe still is best.

**Comment by jpmckinney** [comment]
> We know it from the tender release, because it has a tender.designContest... I'm not sure it's obvious enough for a clueless data explorer, especially if they only look at the award release..

Should we create an issue for this on the standard repo? If nothing else is blocking, is this PR okay to merge?

**Comment by ColinMaudry** [comment]
Yes, OK to merge :rocket:

**Pull request merged**
