### PR TITLE
Mapped remaining fields for F12

### PR DESCRIPTION
**Pull request by ColinMaudry**

### CODE REVIEW

**Comment by jpmckinney** [comment]
I committed my review:

1. Change `tender.designContest.juryMembers` to an array of objects instead of an array of strings, to allow for structure
1. Change nesting from `designContest.description` to `designContest.prizes.description`
1. Clarify how to set `tender.designContest.selectedParticipants.id`
1. Rename `hasPrize` to `hasPrizes`
1. Rename `decisionBindingContracting` to `isBindingJuryDecision`
1. Rename `paymentDetails` to `rewardsDetails`
1. Rename 'contestSelectedParticipant' to 'selectedParticipant'
1. Remove extra quote characters

(2) is because eForms has structured data about prizes, so I thought it appropriate to add a `prizes` object, similar to the structure of `awardCriteria` and `selectionCriteria`.

(6) is because this aligns most closely to BT-45 (Rewards Other), where the payment is a type of reward, e.g. a payment that is made to all participants, just for participating.

Do you agree with the changes?

**Comment by ColinMaudry** [comment]
> (2) is because eForms has structured data about prizes, so I thought it appropriate to add a prizes object, similar to the structure of awardCriteria and selectionCriteria.

I agree, but BG-704 "Reward and jury" is described this way:

> Information about the rewards and the jury in a design contest. **This information may differ per lot**.

I'm not sure how lots and prizes are related, but I guess that in a given procedure, one lot can be subject to a design contest, with prizes, jury, etc. We just associate `.designContest` to Lot too, in addition to associating it to Tender?

**Comment by ColinMaudry** [comment]
It's all good :+1: :slightly_smiling_face:

**Comment by jpmckinney** [comment]
> We just associate .designContest to Lot too, in addition to associating it to Tender?

Yes, as has become common to support both TED and eForms :)

**Pull request merged**
