### PR TITLE
F01 mappings for criteria and techniques fields

### PR DESCRIPTION
**Pull request by ColinMaudry**
**/!\\** I have edited the CSV with LibreOffice, and the trailing `""` have been removed. I hope it's not a problem and won't break the publication.

### CODE REVIEW

**Comment by ColinMaudry** [comment]
With 52643876dbbdf6fc4c8cb3f698c7cf9dfffd2ed6 F01 draft mapping is done. Moving on with F02.

**Comment by ColinMaudry** [comment]
See also:

- [award criteria extension](https://github.com/open-contracting-extensions/ocds_awardCriteria_extension)
- [procurement techniques extension](https://github.com/open-contracting-extensions/ocds_procurement_techniques_extension)

**Comment by jpmckinney** [comment]
Hmm, the trailing "" signals to the build script that the row should not have a mapping column. I'll just add them back while I do my review.

**Comment by ColinMaudry** [comment]
OK, I'll be careful to preserve them from now on.

**Comment by jpmckinney** [comment]
Closing in favor of #5 which is the active branch.

**Pull request closed without merging**
